### ISSUE TITLE
最新版3.10.30，使用自定义播放器无法播放，上一版本3.10.29没有问题。平台mac m1

### ISSUE THREAD

**Issue by rosspsp** [odomu/aliyunpan#103]

**Comment by jlu511** [comment]
把mpv或potplayer文件夹放到小白羊文件夹下的resource文件夹里，设置里面选本地mpv或本地potplayer，就能播放了，然后再设置自定义播放器，也可以播放了，原理不懂，但是好使。

**Comment by odomu** [comment]
@rosspsp 更新试试，手机上改的bug没有测试

**Comment by rosspsp** [comment]
> @rosspsp 更新试试，手机上改的bug没有测试

# 有个新bug：
## 1、mpv播放器，如果视频文件夹下有字幕，可以正常播放视频并正常加载同文件夹下的字幕，但如果没有字幕，则无法播放
## 2、iina和infuse播放器，无论视频文件夹下有无字幕，都可以正常播放视频，但是没有加载同文件夹下的字幕

**Comment by odomu** [comment]
暂时只添加了mpv的字幕和播放历史

**Comment by rosspsp** [comment]
> 暂时只添加了mpv的字幕和播放历史，记忆本地播放器的播放历史无法实现

嗯，但是用mpv播放器的话，如果同文件夹下没有字幕，则无法播放

**Comment by odomu** [comment]
> > 暂时只添加了mpv的字幕和播放历史，记忆本地播放器的播放历史无法实现
> 
> 嗯，但是用mpv播放器的话，如果同文件夹下没有字幕，则无法播放

win下我测试没有问题，到其他平台就有问题了😔

**Comment by rosspsp** [comment]
> > > 暂时只添加了mpv的字幕和播放历史，记忆本地播放器的播放历史无法实现
> > 
> > 
> > 嗯，但是用mpv播放器的话，如果同文件夹下没有字幕，则无法播放
> 
> win下我测试没有问题，到其他平台就有问题了😔

哈哈，麻烦大佬再看看吧

**Comment by jlu511** [comment]
1、mpv播放器，如果视频文件夹下有字幕，可以正常播放视频并正常加载同文件夹下的字幕，但如果没有字幕，则无法播放

**Comment by rosspsp** [comment]
> > > 暂时只添加了mpv的字幕和播放历史，记忆本地播放器的播放历史无法实现
> > 
> > 
> > 嗯，但是用mpv播放器的话，如果同文件夹下没有字幕，则无法播放
> 
> win下我测试没有问题，到其他平台就有问题了😔

mpv播放器，经测试，是否能播放，跟视频文件夹下有无字幕无关，是因为如果这个视频没有播放历史就无法播放，如果有播放历史就可以播放。。。

**Comment by rosspsp** [comment]
> > > 暂时只添加了mpv的字幕和播放历史，记忆本地播放器的播放历史无法实现
> > 
> > 
> > 嗯，但是用mpv播放器的话，如果同文件夹下没有字幕，则无法播放
> 
> win下我测试没有问题，到其他平台就有问题了😔

大佬，需要mac测试平台吗？我可以提供自己的电脑～

**Comment by jlu511** [comment]
确实是新保存的电影无法用mpv播放，之前播放过的就可以播放，跟字幕没关系，跟播放历史有关

**Comment by rosspsp** [comment]
@odomu bug最新版经测试，已解决～
