### ISSUE TITLE
windows 10全量更新总是弹出要打开.blockmap文件

### ISSUE THREAD

**Issue by ublock-ghost** [odomu/aliyunpan#104]
![image](https://github.com/odomu/aliyunpan/assets/89686335/49fee454-9404-4045-99d0-ac8071633248)

**Comment by odomu** [comment]
重新检查更新

**Comment by ublock-ghost** [comment]
> 重新检查更新

![image](https://github.com/odomu/aliyunpan/assets/89686335/9b19f405-766a-46b9-919f-ccf0392654fa)程序关闭了，任务管理器中也没看到，但是一直重试说无法关闭

**Comment by odomu** [comment]
取消安装，去原来软件的resources文件下手动安装

**Comment by ublock-ghost** [comment]
> 取消安装，去原来软件的resources文件下手动安装

还是一样，但任务管理器没找到ali。可能得卸载重新装一下

**Comment by ublock-ghost** [comment]
> 取消安装，去原来软件的resources文件下手动安装

GITHUB下载的安装成功了
