### ISSUE TITLE
安装完最新版本以后，软件打不开，双击没反应。

### ISSUE THREAD

**Issue by zybns** [odomu/aliyunpan#105]
我安装的版本是alixby-3.10.30-win-x64.exe

也试了另外一个版本 也不行，alixby-3.10.30-win.exe。。

我是直接从上一个版本，直接下载现在的最新版本安装的，安装完以后就打不开了。

**Comment by odomu** [comment]
卸载原来的重新安装试试

**Comment by meijuhao** [comment]
> 卸载原来的重新安装试试

反复试过了，问题解决不了。电脑也重启过了。

另外为啥现在我看不到3.10.30的版本下载地址了。

**Comment by odomu** [comment]
我重新打包了

**Comment by meijuhao** [comment]
> 



> 我重新打包了，应该是actions打包的有问题

那我等会  你上传完了，我重新 下载试试

**Comment by odomu** [comment]
> 

你重新下载试试

**Comment by meijuhao** [comment]
> @meijuhao 你重新下载试试

还是打不开，你方便给远程看一下嘛？qq 2960099

**Comment by geeklihui** [comment]
我也打不开，下载的4小时前的最新版64位。系统Win10 22H2 19045

**Comment by JerryLvTvT** [comment]
安装至没有空格目录看看，Aria2通病

**Comment by geeklihui** [comment]
> 安装至没有空格目录看看，Aria2通病

确实解决了，不过安装包默认选择的Program Files就带空格。改到一个无空格的路径就好了。

**Comment by meijuhao** [comment]
我用之前吾爱论坛发的免安装版本打开了软件，然后再安装这个最新版本后，能正常打开了。

**Comment by meijuhao** [comment]
> 我也打不开，下载的4小时前的最新版64位。系统Win10 22H2 19045

64位的版本安装包体积是不是比32位的小。
