### ISSUE TITLE
软件自带更新的一些功能问题

### ISSUE THREAD

**Issue by blibilijojo** [odomu/aliyunpan#106]
先讲一下仔细的经过，5/26就是昨天的时候打开软件更新，此前的版本是v3.10.28版本，首先使用软件内部功能是更新了一次到了下一个版本，然后再次点击更新，更新到再下一个版本，需要两次更新是因为后一个版本是预发布的原因吗？
最后昨天更新到的版本应该是昨天下午的最新版本。
然后今天发现更新了就选择更新，更新到了v3.10.30.stable 版本
![image](https://github.com/odomu/aliyunpan/assets/102420734/d13c0bd7-a370-401f-b5e4-67d9b1ecc121)
然后过了一会这个更新好像撤销了...然后发布了v3.10.30正式版本，然后我再检测更新就这样了：
![image](https://github.com/odomu/aliyunpan/assets/102420734/2ef577d3-06d1-4a86-a5cc-d8c8069dbaa4)
是检测更新的逻辑还是什么之类的错误吧，需要优化一下检测吗？

**Comment by odomu** [comment]
刷版本号

**Comment by blibilijojo** [comment]
> 刷版本号

em，重新安装？

**Comment by blibilijojo** [comment]
> 刷版本号

emmm，重新安装最新版之后这样：
![image](https://github.com/odomu/aliyunpan/assets/102420734/b97d63eb-e999-422b-8541-13e118d614cd)
版本号出问题了吗之前显示的是v3.10.30.stable，GitHub上显示的也是v3.10.30.stable，但是最新版显示的是v3.10.30，还将v3.10.30.stable检测为最新版

**Comment by liuyun198833** [comment]
同问，并且在线更新时经常会出现下图中的问题，得下载后覆盖安装才能正常更新
![image](https://github.com/odomu/aliyunpan/assets/16303973/2645a48e-c1bc-40be-8d65-c29796bc0362)

**Comment by blibilijojo** [comment]
> 同问，并且在线更新时经常会出现下图中的问题，得下载后覆盖安装才能正常更新 ![image](https://user-images.githubusercontent.com/16303973/241352103-2645a48e-c1bc-40be-8d65-c29796bc0362.png)

刚想说这个，应该是把安装程序识别成应用了

**Comment by odomu** [comment]
> > 同问，并且在线更新时经常会出现下图中的问题，得下载后覆盖安装才能正常更新 ![image](https://user-images.githubusercontent.com/16303973/241352103-2645a48e-c1bc-40be-8d65-c29796bc0362.png)
> 
> 刚想说这个，应该是把安装程序识别成应用了

这个最新版重新覆盖安装，后面再更新版本就没有这个问题了

**Comment by odomu** [comment]
> > 刷版本号
> 
> emmm，重新安装最新版之后这样： ![image](https://user-images.githubusercontent.com/102420734/241351770-b97d63eb-e999-422b-8541-13e118d614cd.png) 版本号出问题了吗之前显示的是v3.10.30.stable，GitHub上显示的也是v3.10.30.stable，但是最新版显示的是v3.10.30，还将v3.10.30.stable检测为最新版

这个是为了热更新刷新版本号
