### ISSUE TITLE
自己编译了一个Linux版的，可以运行，不知道怎么放出来。

### ISSUE THREAD

**Issue by daniel-zou** [odomu/aliyunpan#11]
怎么能放到release里，供大家下载？
我自己的系统是Manjaro Linux，运行没问题。

**Comment by lrs95** [comment]
实在不行就放网盘里放出来吧

**Comment by daniel-zou** [comment]
> 实在不行就放网盘里放出来吧

试了，阿里云不让分享压缩包。那就只有百度云了，没有会员会非常慢。压缩包90M+

**Comment by lrs95** [comment]
> > 实在不行就放网盘里放出来吧
> 
> 试了，阿里云不让分享压缩包。那就只有百度云了，没有会员会非常慢。压缩包90M+

试试蓝奏云100M以下是免费的的

**Comment by daniel-zou** [comment]
阿里小白杨版Linux v3.10.24 链接: https://pan.baidu.com/s/1h6kHrTXnIy72vq5DdclNog?pwd=d9vy 提取码: d9vy 
还好文件不是很大，100M以内，百度云限速，有10分钟也差不多了吧。

**Comment by at2008** [comment]
> 阿里小白杨版Linux v3.10.24 链接: https://pan.baidu.com/s/1h6kHrTXnIy72vq5DdclNog?pwd=d9vy 提取码: d9vy 还好文件不是很大，100M以内，百度云限速，有10分钟也差不多了吧。

大佬，解压失败了，能用123盘或者蓝奏 分享一下吗？

**Comment by 2xGBkbvNYW** [comment]
> 

改后缀试试，改成pdf

**Comment by lrs95** [comment]
> > 阿里小白杨版Linux v3.10.24 链接: https://pan.baidu.com/s/1h6kHrTXnIy72vq5DdclNog?pwd=d9vy 提取码: d9vy 还好文件不是很大，100M以内，百度云限速，有10分钟也差不多了吧。
> 
> 大佬，解压失败了，能用123盘或者蓝奏 分享一下吗？

试试这个 https://lrs.lanzoul.com/ielfK0oixg7e

**Comment by at2008** [comment]
> > > 阿里小白杨版Linux v3.10.24 链接: https://pan.baidu.com/s/1h6kHrTXnIy72vq5DdclNog?pwd=d9vy 提取码: d9vy 还好文件不是很大，100M以内，百度云限速，有10分钟也差不多了吧。
> > 
> > 
> > 大佬，解压失败了，能用123盘或者蓝奏 分享一下吗？
> 
> 试试这个 https://lrs.lanzoul.com/ielfK0oixg7e

多谢，这个可以正常解压！

**Comment by lrs95** [comment]
> > > > 阿里小白杨版Linux v3.10.24 链接: https://pan.baidu.com/s/1h6kHrTXnIy72vq5DdclNog?pwd=d9vy 提取码: d9vy 还好文件不是很大，100M以内，百度云限速，有10分钟也差不多了吧。
> > > 
> > > 
> > > 大佬，解压失败了，能用123盘或者蓝奏 分享一下吗？
> > 
> > 
> > 试试这个 https://lrs.lanzoul.com/ielfK0oixg7e
> 
> 多谢，这个可以正常解压！

其实我这个也是下载楼主的包，可能是你下载的包不完整吧

**Comment by jkqxl** [comment]
> > 实在不行就放网盘里放出来吧
> 
> 试了，阿里云不让分享压缩包。那就只有百度云了，没有会员会非常慢。压缩包90M+

阿里云 压缩压成 .exe格式可以分享
