### ISSUE TITLE
自制mac端图标，希望采纳

### ISSUE THREAD

**Issue by rosspsp** [odomu/aliyunpan#113]
### 功能描述 / Features

美化

### 期望实现方式 / How to implement

 
[图标.zip](https://github.com/odomu/aliyunpan/files/11581377/default.zip)

**Comment by odomu** [comment]
![image](https://github.com/odomu/aliyunpan/assets/50035498/8a5033c1-a078-4360-88ac-48166b45beff)

像素有点低

**Comment by rosspsp** [comment]
> ![image](https://user-images.githubusercontent.com/50035498/241397376-8a5033c1-a078-4360-88ac-48166b45beff.png)
> 
> 小图标像素有点低

这套图标是用在mac上的，小图标用于显示在任务栏，我这边测试显示刚刚好

**Comment by rosspsp** [comment]
这是原图
[图片.zip](https://github.com/odomu/aliyunpan/files/11582266/default.zip)

**Comment by kratos9394** [comment]
mac的任务栏图标怎么这么大

**Comment by charley008** [comment]
对对对，超级无敌大
