### ISSUE TITLE
分享导入文件的“提示”重复

### ISSUE THREAD

**Issue by blibilijojo** [odomu/aliyunpan#117]
### 问题描述 / Describe Bugs

如图：
![image](https://github.com/odomu/aliyunpan/assets/102420734/9076a5d2-5f6b-47bb-9bf9-7f6c4c234ba6)
在导入较少文件时（不触发异步导入）导入成功出现，应该算是bug吧，毕竟信息重复了，只需要一个就行了。

### 复现步骤 / How to reproduce

“分享”→“导入过的分享”→任意分享中选择只选择一个文件导入
这样就复现了

### 软件版本 / App version

v3.10.30

### 系统类型 / System type

Windows

**Comment by odomu** [comment]
小bug没有精力修复
