### ISSUE TITLE
“批量重命名”应用后提示重复

### ISSUE THREAD

**Issue by blibilijojo** [odomu/aliyunpan#118]
### 问题描述 / Describe Bugs

我先这样：
![image](https://github.com/odomu/aliyunpan/assets/102420734/2b99358a-5c7b-4834-bf2f-737bd59c1943)
然后“应用添加”，然后显示：
![image](https://github.com/odomu/aliyunpan/assets/102420734/6c2f447c-9098-4039-86ea-5f3b8159a2ad)
只进行了一次批量重命名，却显示“2”
如果“批量重命名”只选择一个文件然后应用：
![image](https://github.com/odomu/aliyunpan/assets/102420734/8e747a84-4487-49bd-abda-ac50a8ace39b)
显示：
![image](https://github.com/odomu/aliyunpan/assets/102420734/745f4654-947f-4a63-84f1-24dec299e679)
这次显示正常
如果我选中多个文件后只选择一个文件重命名：
![image](https://github.com/odomu/aliyunpan/assets/102420734/121ae6e3-8902-4b31-927c-7659876bab09)
显示：
![image](https://github.com/odomu/aliyunpan/assets/102420734/e62f24df-bd15-41bc-a089-9e1343b4cc0c)
总之就是批量重命名成功提示显示次数不正常问题

### 复现步骤 / How to reproduce

问题描述里应该算是讲了

### 软件版本 / App version

v3.10.30

### 系统类型 / System type

Windows

**Comment by odomu** [comment]
小bug没有精力修复
