### ISSUE TITLE
在选择了“自定义播放器”和“播放原始的文件”后添加一个设置，功能：对于大于一定分辨率的视频进行转码播放

### ISSUE THREAD

**Issue by blibilijojo** [odomu/aliyunpan#121]
### 功能描述 / Features

对于分辨率高于显示器分辨率的视频，播放原始文件显然有些缺点，占用高，主要的是分辨率高了也没啥用
建议在“在线预览”中选择了“自定义播放器”和“播放原始的文件”后添加一个设置，功能：对于大于一定分辨率的视频进行转码播放

### 期望实现方式 / How to implement

![image](https://github.com/odomu/aliyunpan/assets/102420734/931924bc-1ffd-4d08-90e6-5ba1f1050166)
这里添加一个设置，可以将高于一定分辨率的视频自动转为“播放转码后视频”，分辨率是加一个选择还是检测屏幕分辨率都行，就是如果遇到不是正常比例的视频（方形和不是一般比例的长方形）希望能检测

**Comment by odomu** [comment]
和播放转码视频功能重复，无法实现码率判断
