### ISSUE TITLE
自动签到和自动更新每日一次

### ISSUE THREAD

**Issue by wqiucheng** [odomu/aliyunpan#128]
### 功能描述 / Features

现在设置打开时签到和更新，每次打开都会进行。是否可以设置为每日只进行一次？

### 期望实现方式 / How to implement

略

**Comment by odomu** [comment]
自动签到本来就是每日一次，自动更新为启动时检查更新

**Comment by wqiucheng** [comment]
启动时每次都会有提示的，每日一次指的是每日一次后后面不提示
