### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by wqiucheng** [odomu/aliyunpan#129]
### 功能描述 / Features

下载引擎是基于Aria2的，是否可以新增一个下载文件功能，如下页面。迅雷有一个功能就是可以下载文件到云盘，所以在这个对话框也可以增加一个可选项，下载到本地/云盘（就是下载后再上传到当前路径）。这将会大大增强现有功能。
![image](https://github.com/odomu/aliyunpan/assets/131881100/ec79156d-fe2e-4bc5-a8d3-d9a5265c3768)

### 期望实现方式 / How to implement

略

**Comment by blibilijojo** [comment]
迅雷是下载器，这个是网盘软件，咋可能一样.......

**Comment by wqiucheng** [comment]
迅雷网盘有一个功能，就是添加下载链接到网盘，小白羊基于Aria2下载引擎，这个功能并不难添加。

**Comment by blibilijojo** [comment]
> 迅雷网盘有一个功能，就是添加下载链接到网盘，小白羊基于Aria2下载引擎，这个功能并不难添加。

额.........你的意思就是在迅雷这个下载工具中可以选择下载到网盘中？
