### ISSUE TITLE
软件提示 aria2 创建文件时失败

### ISSUE THREAD

**Issue by xdtxAM** [odomu/aliyunpan#130]
### 问题描述 / Describe Bugs

点击下载文件，在传输选项卡里面提示aria2c创建文件时失败

### 复现步骤 / How to reproduce

点击下载文件，在传输选项卡里面提示aria2c创建文件时失败

### 日志提交 / Relevant log output

29 11:07:30 : success : 小白羊启动
28 11:58:10 : success : 小白羊启动
29 21:16:41 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at oe.emit (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:52799)
    at ue.onerror (file:///Applications/alixby.app/Contents/Resources/app.asar/dist/index.js:75:60620)
29 21:16:41 : danger : Uncaught Error: Unhandled error. (undefined)
29 21:16:38 : danger : onerror 

### 软件版本 / App version

最新的版本

### 系统类型 / System type

Windows

**Comment by xdtxAM** [comment]
## 系统是 macOS 选择错了。

**Comment by odomu** [comment]
需要在设置下载路径，否则没有权限创建文件夹
