### ISSUE TITLE
内置播放器播放列表都显示undefined

### ISSUE THREAD

**Issue by Theodore-98** [odomu/aliyunpan#131]
### 问题描述 / Describe Bugs

内置播放器播放列表都显示undefined
测试了视频都是这样，上个版本还有一些正常显示

### 复现步骤 / How to reproduce

无

### 日志提交 / Relevant log output

无

### 软件版本 / App version

v3.10.31

### 系统类型 / System type

Windows

**Comment by odomu** [comment]
昨天打包的有bug，
