### ISSUE TITLE
相册功能

### ISSUE THREAD

**Issue by rosspsp** [odomu/aliyunpan#133]
### 功能描述 / Features

增加相册功能，对相册内的照片进行管理

### 期望实现方式 / How to implement

在【网盘】和【传输】之间增加【相册】

<img width="637" alt="iShot_2023-05-30_00 06 03" src="https://github.com/odomu/aliyunpan/assets/73610222/5af86e5e-c4fe-4f69-a407-c5f2c4b91383">

**Comment by odomu** [comment]
请使用网页或者手机版管理相册
