### ISSUE TITLE
openapi时好时坏，前台报错【视频地址解析失败，操作取消】，后台日志：HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403

### ISSUE THREAD

**Issue by liuyun198833** [odomu/aliyunpan#134]
### 问题描述 / Describe Bugs

openapi时好时坏，前台报错【视频地址解析失败，操作取消】，后台日志：HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403

同时有两个问题：
1、在视频地址解析失败的情况下关闭openapi就可以播放，速度还可以，但是再次启动的时候速度就不行。
2、新登录账号时，RefreshToken按正常情况应该为空，但是有时会直接显示已登录账号的RefreshToken

不知以上报错跟上面的两个问题是否有关。

### 复现步骤 / How to reproduce

点击视频，弹出【视频地址解析失败，操作取消】提示

### 日志提交 / Relevant log output

HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403

### 软件版本 / App version

v3.10.31.fix

### 系统类型 / System type

Windows

**Comment by odomu** [comment]
最新版本测试一下

**Comment by liuyun198833** [comment]
@odomu  感谢大佬，已完美解决
