### ISSUE TITLE
拖动文件夹到软件ui上面，无法上传。

### ISSUE THREAD

**Issue by LIUBANGJIAN** [odomu/aliyunpan#141]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue / No similar or related issues
- [X] #143

### 问题描述 / Describe Bugs

拖动文件夹到软件ui上面，无法上传。

### 复现步骤 / How to reproduce

拖动文件夹到软件ui上面，无法上传。

### 软件版本 / App version

阿里云盘小白羊v3.10.33

### 系统类型 / System type

Windows

### 系统版本 / System Version

win10 2019 ltsc

**Comment by NEARWN** [comment]
新版本出现了同样问题，可否修复，谢谢

**Comment by odomu** [comment]
没有考虑到管理员权限运行权限太高，无法拖拽低权限的文件，稍后会重新打包

**Comment by odomu** [comment]
重新下载最新版本
