### ISSUE TITLE
win7任务栏固定与正在运行程序不重叠

### ISSUE THREAD

**Issue by blibilijojo** [odomu/aliyunpan#145]
### 确认问题 / Assignments

- [x] 不存在相似或相关的issue / No similar or related issues
- [X] 最新版本是否存在此问题 / Latest app does not work
- [X] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

![image](https://github.com/odomu/aliyunpan/assets/102420734/3ddaf938-7a1d-422e-b7d2-c963e699d4c0)
win7，就是这样

### 复现步骤 / How to reproduce

win7固定程序，打开程序就这样

### 软件版本 / App version

v3.10.33

### 系统类型 / System type

Windows

### 系统版本 / System Version

win7

**Comment by blibilijojo** [comment]
还有就是我想说一下代码更新提交那个能不能用中文啊，阿里云盘都是中国用户没必要英文啊

**Comment by odomu** [comment]
![image](https://github.com/odomu/aliyunpan/assets/50035498/f89eed97-f2c7-4f35-a159-bf763c866956)
