### ISSUE TITLE
refreshtoken 自动更改，导致无法下载和看电影

### ISSUE THREAD

**Issue by jlu511** [odomu/aliyunpan#148]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue / No similar or related issues
- [X] 最新版本是否存在此问题 / Latest app does not work
- [X] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

扫码登录，在设置里refreshtoken 设置alist获得的token，可以正常看电影和下载上传。但使用一段时间之后，看电影提示地址解析错误，发现 是refreshtoken发生改变，删除refreshtoken，同时删除accesstoken，重新填入refreshtoken，就可正常观看电影。不会提示地址解析错误。但过一段时间又会发生。

### 复现步骤 / How to reproduce

过一段时间就会发生，几个小时，重复出现，从32版本开始。

### 日志提交 / Relevant log output

03 16:22:00 : success : 小白羊启动
03 16:17:20 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
03 16:05:52 : success : 小白羊启动
03 14:20:18 : success : 小白羊启动
03 11:54:06 : success : 小白羊启动
03 02:44:28 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
03 02:23:21 : success : 小白羊启动
02 23:33:33 : success : 小白羊启动
02 23:24:48 : success : 小白羊启动
02 19:29:50 : success : 小白羊启动
02 19:10:55 : success : 小白羊启动
02 14:54:04 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
02 14:53:07 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
02 14:53:02 : success : 小白羊启动
02 14:52:47 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
02 14:52:03 : success : 小白羊启动
02 14:43:56 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
02 14:43:27 : success : 小白羊启动
02 14:42:51 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
02 14:42:36 : success : 小白羊启动
02 12:07:00 : warning : HttpError1 message=Network Error
02 12:06:52 : success : 小白羊启动
02 03:25:25 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
02 03:25:15 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
02 03:25:12 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
02 03:25:03 : success : 小白羊启动
02 03:24:42 : success : 小白羊启动
02 03:24:02 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
02 03:23:56 : success : 小白羊启动
02 03:23:41 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
02 03:23:34 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
02 03:23:26 : success : 小白羊启动
02 03:01:17 : success : 小白羊启动
02 00:01:18 : success : 小白羊启动
01 23:58:56 : success : 小白羊启动
01 23:57:57 : success : 小白羊启动
01 23:57:06 : success : 小白羊启动
01 23:54:19 : success : 小白羊启动
01 23:02:54 : success : 小白羊启动

### 软件版本 / App version

v3.10.33

### 系统类型 / System type

Windows

### 系统版本 / System Version

win10

**Comment by odomu** [comment]
@jlu511 你试试看新版本，我不确定是否正常

[123pan下载](https://www.123pan.com/s/YNU7Vv-iz6F3.html)

**Comment by jlu511** [comment]
> @jlu511 你试试看新版本，我不确定是否正常
> 
> [123pan下载](https://www.123pan.com/s/YNU7Vv-iz6F3.html)

好的，我先试用看看是否还出现问题，谢谢大佬

**Comment by liuyun198833** [comment]
@odomu 
用大佬提供的123pan中的程序进行了测试，依然还会出现 HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403错误，但出错的频率比以前要少。希望大佬能继续优化一下
