### ISSUE TITLE
token问题

### ISSUE THREAD

**Issue by 6su6** [odomu/aliyunpan#153]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue / No similar or related issues
- [ ] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

填入refresh token之后，过几个小时重新打开软件又得再次填写。

### 复现步骤 / How to reproduce

填入refresh token之后，过几个小时重新打开软件又得再次填写。

### 软件版本 / App version

最新

### 系统类型 / System type

Windows

### 系统版本 / System Version

win11

**Comment by at2008** [comment]
是不是登录了多个账号？但账户正常，多账户异常！

**Comment by 6su6** [comment]
> 是不是登录了多个账号？但账户正常，多账户异常！

没有呀，就登录了一个账号
