### ISSUE TITLE
一些反馈

### ISSUE THREAD

**Issue by wqiucheng** [odomu/aliyunpan#163]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue / No similar or related issues
- [ ] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

1.使用网页播放器播放报rejection The play0 request was interrupted by a new load request. https://goo.gl/LdLk22 的错误（在选集中多切换几次就可以复现）
2.下载线程数，OpenAPI官方限制请求数，线程数设置的过高会报错Too Many Requests，这个不建议自定义，最好内部固定，避免不必要的麻烦，以前V2中小白羊也固定了。
3.登陆时在原有登录弹窗基础上，第二个建议弹第二个OpenAPI的登录弹窗（形式和第一个差不多），一个是现在不配OpenAPI基本没法用，另一个放在设置中去设置，在开始时加一个初始化还好点。另外设置中深色模式能设为默认项吧（绝大多数都会设为深色）

### 复现步骤 / How to reproduce

略

### 软件版本 / App version

最新

### 系统类型 / System type

Windows

**Comment by maomaochong199** [comment]
最新版alixby-3.23.60617下载的倒计时显示不正确怎么办，一直显示只剩1秒
