### ISSUE TITLE
无法使用自定义播放器播放视频

### ISSUE THREAD

**Issue by rosspsp** [odomu/aliyunpan#165]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue / No similar or related issues
- [X] 最新版本是否存在此问题 / Latest app does not work
- [X] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

[v3.10.32]版本，使用自定义播放器播放视频，是正常的。之后版本，会报错，点击报错信息，软件自动退出。

### 复现步骤 / How to reproduce

报错信息截图如下：
<img width="297" alt="iShot_2023-06-06_12 17 59" src="https://github.com/odomu/aliyunpan/assets/73610222/eecbe4c0-935d-442b-8569-76bc49c6973a">

### 日志提交 / Relevant log output

无报错日志

### 软件版本 / App version

[v3.10.33]、[v3.23.60522]

### 系统类型 / System type

Mac

### 系统版本 / System Version

macos 13.4

**Comment by odomu** [comment]
https://github.com/odomu/aliyunpan/suites/13395705492/artifacts/733384775

**Comment by rosspsp** [comment]
> 

不报错了，但是依然无法播放，播放器闪退，测试了mpv、iina、infuse

**Comment by odomu** [comment]
[app.asar.zip](https://github.com/odomu/aliyunpan/suites/13397238910/artifacts/733587730)

**Comment by rosspsp** [comment]
> 
替换之后，测试没有问题了。
