### ISSUE TITLE
【OpenApi】一直加载用户或者提示网络请求超时

### ISSUE THREAD

**Issue by JessBobby** [odomu/aliyunpan#170]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue / No similar or related issues
- [X] 最新版本是否存在此问题 / Latest app does not work
- [X] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

无法完成在线播放 提示网络请求超时。加载用户信息也要好几分钟才能实现

### 复现步骤 / How to reproduce

打开

### 软件版本 / App version

最新的

### 系统类型 / System type

Windows

### 系统版本 / System Version

Win10 21H2 19044.1889

**Comment by odomu** [comment]
现在alist的方式获取OpenApi Token可能已经被阻断，需要挂梯子才能访问

**Comment by LIUBANGJIAN** [comment]
> 现在alist方式获取OpenApi的**RefreshToken**可能已经被阻断，如果无法访问需要挂梯子才能访问

不是吧?这开个下载软件还要挂梯子？流量会全跑梯子了吗？大佬会出完美解决方案吗？

**Comment by odomu** [comment]
新授权链接
https://api.xhofe.top/alist/ali_open/token
