### ISSUE TITLE
官方api下载部分文件错误

### ISSUE THREAD

**Issue by cancundeyingzi** [odomu/aliyunpan#171]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue / No similar or related issues
- [X] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

![image](https://github.com/odomu/aliyunpan/assets/73635883/6a6a79cf-d483-4839-8458-381e4ac6df8b)
非网络问题,alist正常

### 复现步骤 / How to reproduce

![image](https://github.com/odomu/aliyunpan/assets/73635883/b5c25830-bea7-405a-950a-3d165d1edf9b)

### 日志提交 / Relevant log output

`14 19:48:24 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
14 19:48:13 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
14 19:46:10 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
14 19:45:29 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
14 19:45:28 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
14 19:45:27 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
14 19:45:25 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
14 19:44:33 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
14 19:44:27 : warning : HttpError4 status=403 code=ForbiddenDriveNotValid message=Request failed with status code 403
14 19:38:20 : success : 小白羊启动
14 19:34:08 : success : 小白羊启动
12 11:45:09 : success : 小白羊启动
09 20:03:16 : success : 小白羊启动
08 21:00:33 : success : 小白羊启动
07 21:17:41 : success : 小白羊启动
07 19:35:33 : success : 小白羊启动
07 19:26:16 : success : 小白羊启动
25 17:06:28 : warning : ApiGetFile err=64468a6d390302b2e68a43228c20af32ffb6456a 404
`

### 软件版本 / App version

3.23.61413

### 系统类型 / System type

Windows

### 系统版本 / System Version

win11,22h2

**Comment by odomu** [comment]
无法复现，**Crtl  + Shift +  F12打开控制台，选择网络截图错误的网络请求**

**Comment by cancundeyingzi** [comment]
> 无法复现，**Crtl + Shift + F12打开控制台，选择网络截图错误的网络请求**
![image](https://github.com/odomu/aliyunpan/assets/73635883/a93183f2-6108-4ebd-92e5-f6855527d5f3)

![image](https://github.com/odomu/aliyunpan/assets/73635883/4d389ac6-962c-4d57-96f1-4498406a60d7)
> 打开关闭一次OpenApi, 删除RefreshToken并重新获取
之前已经重试多次

目前正在清除数据重置中

**Comment by cancundeyingzi** [comment]
清除数据有效,感谢
