### ISSUE TITLE
BUG：下载速度慢、MPV缓存问题

### ISSUE THREAD

**Issue by jkqxl** [odomu/aliyunpan#181]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue / No similar or related issues
- [ ] 最新版本是否存在此问题 / Latest app does not work
- [X] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

版本：3.23.61413 刚更新的最新版未测试，看说明似乎有所改善，不确定。

下载速度总是提不起来，最多总速度能有10MB/s 左右，而无法达到满速度的40MB/s。

如果说下载速度勉强能让人接受的话，那调用MPV的播放体验就要让人崩溃了。

偶尔也正常，但连续播放几个视频后就不确定了，看MPV进度条显示未有缓存。

说一千，道一万，同样是基于 Electro 的应用，蜗牛则没有上述的问题，别人家的孩子。。。

如果作者想要参考解决，可参考以下地址
https://github.com/liupan1890/aliyunpan/issues/901
https://www.aliyundrive.com/s/fqu79Z2dBbu/folder/6404068e11271d69f51b4c25a4bf817da60d5f72

### 复现步骤 / How to reproduce

调用Mpv缓存问题：

未进行具体尝试，但可以确定的是，这个问题会经常出现，及其烦人

### 日志提交 / Relevant log output

ApiGetFile err=6493ba558c27e2a3253b4ceeaf37abfac452f0a8 404
HttpError4 status=404 code=NotFound.File message=Request failed with status code 404
ApiGetFile err=6493ba56817859c330dc4bf0a025a8f2d3954880 404
HttpError4 status=404 code=NotFound.File message=Request failed with status code 404
ApiGetFile err=6493ba5589936d70910f4607ae744cfc30bc9556 404
HttpError4 status=404 code=NotFound.File message=Request failed with status code 404

### 软件版本 / App version

PC 小白羊 v3.23.61413

### 系统类型 / System type

Windows

### 系统版本 / System Version

Windows 10 专业版 22H2 19045.2604

**Comment by jkqxl** [comment]
v3.23.62510 测试

依然会出现 MPV缓存问题

日志
26 20:36:39 : warning : HttpError1 message=Network Error
26 20:36:37 : danger : unhandledrejection 
//== Error ==//
 Network Error 
//== Stack ===//
 AxiosError: Network Error
    at te.onerror (file:///S:/Tool%20-Down/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98%E5%B0%8F%E7%99%BD%E7%BE%8A%E7%89%88v3/resources/app.asar/dist/index.js:91:5036)
26 20:36:37 : danger : unhandledrejection
26 20:30:25 : success : 小白羊启动
26 10:00:30 : warning : ApiGetFile err=626955949b9582c9974e4491b126a02134257c77 404
26 10:00:30 : warning : HttpError4 status=404 code=NotFound.File message=Request failed with status code 404

**Comment by odomu** [comment]
出错时使用Ctrl + Shift + F12打开DevTools，截图错误的网络请求

**Comment by jkqxl** [comment]
> 1. 出错时使用Ctrl + Shift + F12打开DevTools，截图错误的网络请求
> 2. 打开关闭一次OpenApi, 删除RefreshToken并重新获取
> 3. 尽量不要将软件安装到中文路径，以及安装路径不要有空格
> 
> [Wiki](https://github.com/odomu/aliyunpan/wiki/%E8%BD%AF%E4%BB%B6%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)

之前是没有使用 OpenApi 的，尝试了下，但 RefreshToken 使用 Alist 打开 显示出错，0x800401f5

**Comment by jkqxl** [comment]
> 1. 出错时使用Ctrl + Shift + F12打开DevTools，截图错误的网络请求
> 2. 打开关闭一次OpenApi, 删除RefreshToken并重新获取
> 3. 尽量不要将软件安装到中文路径，以及安装路径不要有空格
> 
> [Wiki](https://github.com/odomu/aliyunpan/wiki/%E8%BD%AF%E4%BB%B6%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)
![Snipaste_2023-06-28_08-52-07](https://github.com/odomu/aliyunpan/assets/72729140/2c45f1e4-964f-4d9a-b77a-fe2e9e062e58)
不清楚该怎么看出错，还是那个MPV无法缓存的问题，这次使用的是最新版 v3.23.62621

日志
OpenApiTokenRefreshAccount err=400 Invalid request
HttpError4 status=400 code=Invalid request message=Request failed with status code 400

**Comment by odomu** [comment]
改一下Oauth链接 https://api.xhofe.top/alist/ali_open/token

**Comment by jkqxl** [comment]
> https://api.xhofe.top/alist/ali_open/token

之前就是在改的前提上出现错误的
![Snipaste_2023-06-28_18-11-46](https://github.com/odomu/aliyunpan/assets/72729140/dce86661-8877-49ff-bc06-c6dea6465716)

**Comment by odomu** [comment]
重置一下软件

**Comment by jkqxl** [comment]
> 重置一下软件

mpv 缓存问题 通过浏览器网址获取令牌后已经解决，感谢作者的努力，之前并不清楚必须开启  OpenApi  才行。
