### ISSUE TITLE
自定义播放器播放视频文件时自动将当前文件夹下所有视频文件载入列表

### ISSUE THREAD

**Issue by blibilijojo** [odomu/aliyunpan#183]
### 功能描述 / Features

![image](https://github.com/odomu/aliyunpan/assets/102420734/9fd3b166-a99c-4043-aaa7-b145cd013154)
打开一个其中文件
![image](https://github.com/odomu/aliyunpan/assets/102420734/968d705f-e930-4869-a558-3727476e2731)
我要是想一口气全看完还得手动点，要是能直接把其他文件也载入播放列表就好了

### 期望实现方式 / How to implement

上述

**Comment by odomu** [comment]
无法实现
