### ISSUE TITLE
Mac 的状态栏图标大小异常

### ISSUE THREAD

**Issue by douseful** [odomu/aliyunpan#184]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [X] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

Mac 的任务栏图标大小异常
<img width="347" alt="image" src="https://github.com/odomu/aliyunpan/assets/52767905/3039e886-a7cf-455b-a22c-242db4b67f28">

### 复现步骤 / How to reproduce

每次打开……

### 软件版本 / App version

v3.23.62621

### 系统类型 / System type

Mac

**Comment by odomu** [comment]
[这里你改下判断](https://github.com/odomu/aliyunpan/blob/70d475a46c34fdebfbfbb1867a6fb7f15866d8f0/electron/main/utils/mainfile.ts#L46)
