### ISSUE TITLE
创建Aria任务失败断开连接

### ISSUE THREAD

**Issue by wiete** [odomu/aliyunpan#186]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [X] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

![image](https://github.com/odomu/aliyunpan/assets/88014545/e99d79dc-6657-4554-88f9-e240230e078a)

### 复现步骤 / How to reproduce

怎么办？

### 软件版本 / App version

centos7

### 系统类型 / System type

Linux

**Comment by bpint** [comment]
一样的错误，日志里的错误信息是：

```log
AriaAddUrlCannot read properties of undefined (reading '2') //== Error ==// Cannot read properties of undefined (reading '2') //== Stack ===// TypeError: Cannot read properties of undefined (reading '2') at AriaAddUrl (file:///opt/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98%E5%B0%8F%E7%99%BD%E7%BE%8A/resources/app.asar/dist/index.js:102:74823) at async DownDAL.aSpeedEvent (file:///opt/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98%E5%B0%8F%E7%99%BD%E7%BE%8A/resources/app.asar/dist/index.js:120:15252)
```
