### ISSUE TITLE
上传文件无法跑满100M

### ISSUE THREAD

**Issue by rxmnog** [odomu/aliyunpan#188]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [X] 最新版本是否存在此问题 / Latest app does not work
- [X] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

Refresh Token已经填写，下载1000M满速没问题，上传始终只有50M左右

### 复现步骤 / How to reproduce

上传任意一个文件，都无法跑满100M

### 软件版本 / App version

3.23.62621

### 系统类型 / System type

Windows

### 系统版本 / System Version

win11专业工作站版 22h2 22631.1906

**Comment by odomu** [comment]
你的宽带是**上下对等**的吗

**Comment by cancundeyingzi** [comment]
> 你的宽带是**上下对等**的吗

对等也跑不到,怀疑是阿里云限速了,用过speedtest.net/cn,360测速/花瓣测速/全球网测,都能跑(家里100mbps/公司900mbps).但是阿里上传始终只有3MB/s
