### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by wqcblog** [odomu/aliyunpan#19]
作者，您好，谢谢你的开发
有如下几个问题反馈一下
1.侧边栏没有折叠按钮，导致折叠很不方便
![image](https://user-images.githubusercontent.com/82157125/221353456-8133edc2-fabb-4e71-8236-6a4dc2bead5b.png)

2.点高级搜索会有报错弹窗，但高级搜索功能没有问题
![image](https://user-images.githubusercontent.com/82157125/221353531-13bf3324-5dcb-4383-a87d-cb09bcc8fd3b.png)

此外建议：
由于原作者留了一些功能并没有开发，例如相册及插件中的某些插件，能否先删掉这些UI显示。

**Comment by onvz** [comment]
我也发现一个，，下载队列中，只能全选，不能单选

**Comment by lrs95** [comment]
> 我也发现一个，，下载队列中，只能全选，不能单选

这个问题已经修复了，下载最新版

**Comment by onvz** [comment]
> > 我也发现一个，，下载队列中，只能全选，不能单选
> 
> 这个问题已经修复了，下载最新版
好的，无敌感谢维护，又可以愉快的用小白羊了
有个无关痛痒的小问题，

同时下载某剧多个剧集的时候，可以按照集数从小到大顺序下载吗？ 这样同时下载观看的时候会方便很多

**Comment by daniel-zou** [comment]
> 

你先排好序，再下载就按照你排序的顺序下载了。
