### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by wqiucheng** [odomu/aliyunpan#191]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [X] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

下载报错，手动选中相关下载任务->开始，又可以正常下载
![image](https://github.com/odomu/aliyunpan/assets/131881100/e5be03c9-1b2a-4f8a-b5f1-ac1616f6d709)
![image](https://github.com/odomu/aliyunpan/assets/131881100/1fb0009d-eb89-41d1-90ba-ca02b0b2588a)

### 复现步骤 / How to reproduce

略

### 软件版本 / App version

最新

### 系统类型 / System type

Windows

**Comment by odomu** [comment]
不要同时下载太多的文件，一次不要超过5个，官方QPS限制下载量

**Comment by wqiucheng** [comment]
就是默认的设置，没有动它

**Comment by wqiucheng** [comment]
以前没遇到这种错误过，以前的too many requests解决后就开始出现这种错误了，集中在下载前期创建下载任务阶段时出现。

**Comment by odomu** [comment]
这个没有办法， 我测试过没有问题，我只是让出错原因显示了

**Comment by wqiucheng** [comment]
是否有自动重试机制呢？因为这个手动点选中点开始就解决了，有点悬学。

**Comment by odomu** [comment]
就是单位时间内获取链接次数太多了

**Comment by wqiucheng** [comment]
我明白您的意思，我指的是能否在本次下载任务结束时自动重试这些未能完成的任务，一般就不会出现这样并发报错了。

**Comment by wqiucheng** [comment]
因为我试下每次就是创建任务前期的某些文件有这些错误，手动选中点开始就可以正常。所以能否有一个重试机制，在整个下载任务结束时重试之前因429报错的任务，报错原因先显示为等待重试之类的，如果重试成功就ok，重试失败就显示下载失败之类的。
