### ISSUE TITLE
看到这段文字“阿里云盘小白羊【最终版-不再更新】- 请重新下载安装”，请问大佬是要弃坑了吗？

### ISSUE THREAD

**Issue by LIUBANGJIAN** [odomu/aliyunpan#198]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [ ] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

看到这段文字“阿里云盘小白羊【最终版-不再更新】- 请重新下载安装”，请问大佬是要弃坑了吗？

### 复现步骤 / How to reproduce

看到这段文字“阿里云盘小白羊【最终版-不再更新】- 请重新下载安装”，请问大佬是要弃坑了吗？

### 日志提交(截取部分日志，不要太长) / 使用Ctrl+Shift+F12打开DevTools截图错误的网络请求

看到这段文字“阿里云盘小白羊【最终版-不再更新】- 请重新下载安装”，请问大佬是要弃坑了吗？

### 软件版本 / App version

3.23

### 系统类型 / System type

Windows

### 系统版本 / System Version

WIN10

**Comment by blibilijojo** [comment]
开了议题肯定就会更新我觉得
