### ISSUE TITLE
aria2c 创建文件夹失败

### ISSUE THREAD

**Issue by Dgnic** [odomu/aliyunpan#20]
![Snipaste_2023-02-25_21-07-50.jpg](https://p.sda1.dev/10/5fa87ab29adca427d929f86c961b6d55/Snipaste_2023-02-25_21-07-50.jpg)

平台为 Windows。
下载文件夹已经设置过了，路径为「E:\视频\电影」，下面三个选项都勾选。

补充：
问题已经解决，刚刚又试了一下，发现关掉设置-下载里的「新建下载任务时按照网盘完整路径保存」选项，就可以成功下载，不过原因未知。

**Comment by daniel-zou** [comment]
哪个平台啊？windows还是Linux？设置了下载文件夹没有？在设置里面有个下载文件夹，选一下。
啥也不说明，就贴一张图，我要是作者，有精力也不回。

**Comment by Dgnic** [comment]
> 哪个平台啊？windows 还是 Linux？设置了下载文件夹没有？在设置里面有个下载文件夹，选一下。 啥也不说明，就贴一张图，我要是作者，有精力也不回。

原先认为这个软件目前只有 Win 平台，抱歉是我疏忽了，平台为 Windows 没错，我在主楼补充了一些相关的信息。
不过目前问题已经解决了，刚刚又试了一下，发现关掉设置-下载里的「新建下载任务时按照网盘完整路径保存」选项，就可以成功下载了，但是原因不太清楚。

**Comment by HuenYin** [comment]
我在mac x64下也出现这个问题：“aria2c创建文件夹失败,请设置保存路径”
