### ISSUE TITLE
资源盘与备份盘

### ISSUE THREAD

**Issue by Riley1025** [odomu/aliyunpan#204]
### 功能描述 / Features

大佬您好，现在阿里云盘更新后出现了备份盘与资源盘的分类，咱们之前资源保存都是在备份盘，而现在从网页或他人链接中保存资源都会默认保存进资源盘导致打开小白羊无法看到保存的资源，所以希望也添加进该分类；
并且现在阿里云盘官网app将该步骤”资源盘中文件转移到备份盘“非常繁琐，想麻烦大佬看看能不能有所优化。

### 期望实现方式 / How to implement

我看隔壁https://github.com/gaozhangmin/aliyunpan 他的小白羊已经支持了备份盘与资源盘的分类；

**Comment by devyujie** [comment]
已更新 https://github.com/odomu/aliyunpan/releases/tag/v3.23.80718 ，感谢作者。

**Comment by cancundeyingzi** [comment]
阿里发神经我大号都在资源库,小号都在备份盘

**Comment by cancundeyingzi** [comment]
但是alist和小白羊都能读取
