### ISSUE TITLE
感谢作者对于小白羊的接受维护，不知以后是否会继续接手维护呢？一些BUG的反馈。。。

### ISSUE THREAD

**Issue by jkqxl** [odomu/aliyunpan#21]
软件：v3.10.24 

测试：播放视频、下载都没问题

启动日志
HttpError4 status=0 code=undefined message=Network Error
HttpError0 message=Network Error
很奇怪，不知道哪里还有问题

其它的一些问题
1.下载在状态栏并没有显示下载/上传速度
2.取消在顶部显示完整文件夹路径，但文件界面上方还是空了一行

**Comment by Orangelu179** [comment]
请问问题解决了么?一直只有600kb，有时日志还会报：
ApiFileDownloadUrl1 err=63e4e0a52093bb4a5f444098b698421aa324f7e3 403
