### ISSUE TITLE
播放视频时调用第三方本地播放器提示失败

### ISSUE THREAD

**Issue by Lancercx** [odomu/aliyunpan#211]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [ ] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

调用第三方本地播放器播放视频失败，提示视频解析失败

### 复现步骤 / How to reproduce

在设置中选择在线预览后，设置视频播放器路径后，再去点击视频播放时会提示：视频地址解析失败，播放取消。
另一个问题是每次点击播放视频时会弹出一个选择一个文件选择一个位置的弹出框，这个框好像只能显示文件夹，显示不了文件，这个能取消调吗。每次都选不了文件，只能再这个弹出框，弹出后点击取消，才能解析视频播放，有点麻烦。也不方便。

### 日志提交(截取部分日志，不要太长) / 使用Ctrl+Shift+F12打开DevTools截图错误的网络请求

11 18:51:06 : danger : InvalidParameter.ShareId,DriveId The input parameter share_id, drive_id is not valid. update file request does not contain share_id or drive_id
11 18:50:25 : success : 小白羊启动
11 18:42:18 : success : 小白羊启动
11 18:41:55 : success : 小白羊启动
11 18:38:43 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
11 18:38:43 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
11 18:38:43 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
11 18:38:43 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
11 18:38:31 : success : 小白羊启动
11 18:37:38 : success : 小白羊启动

### 软件版本 / App version

3.23.81112

### 系统类型 / System type

Windows

### 系统版本 / System Version

win10

**Comment by odomu** [comment]
请关闭手动选择字幕文件
![image](https://github.com/odomu/aliyunpan/assets/50035498/2c80500f-6da6-495a-8249-653d832b1f9c)
