### ISSUE TITLE
热更新之后打开软件窗口无法正常显示

### ISSUE THREAD

**Issue by HumanMus1c** [odomu/aliyunpan#212]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [ ] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

打开软件弹出检测到新版本窗口，点击热更新之后再启动软件就是如下图片所示
![image](https://github.com/odomu/aliyunpan/assets/46023154/0737bece-7970-41f5-a6c6-71a877f35c2a)

完整内容如下：
velLoadingTimeOut:1e4,levelLoadingMaxRetry:4,levelLoadingRetryDelay:1e3,levelLoadingMaxRetryTimeout:64e3,fragLoadingTimeOut:2e4,fragLoadingMaxRetry:6,fragLoadingRetryDelay:1e3,fragLoadingMaxRetryTimeout:64e3},timelineConfig()),{},{subtitleStreamController:SubtitleStreamController,subtitleTrackController:SubtitleTrackController,timelineController:TimelineController,audioStreamController:AudioStreamController,audioTrackController:AudioTrackController,emeController:EMEController,cmcdController:CMCDController,contentSteeringController:ContentSteeringController});function timelineConfig(){return{cueHandler:Cues,enableWebVTT:!0,enableIMSC1:!0,enableCEA708Captions:!0,captionsTextTrack1Label:"English",captionsTextTrack1LanguageCode:"en",captionsTextTrack2Label:"Spanish",captionsTextTrack2LanguageCode:"es",captionsTextTrack3Label:"Unknown CC",captionsTextTrack3LanguageCode:"",captionsTextTrack4Label:"Unknown

### 复现步骤 / How to reproduce

1.打开软件
2.弹出检测到新版本窗口，点击热更新

### 日志提交(截取部分日志，不要太长) / 使用Ctrl+Shift+F12打开DevTools截图错误的网络请求

![image](https://github.com/odomu/aliyunpan/assets/46023154/158553a5-b6b3-4145-b41d-d23ec3e7de4a)

### 软件版本 / App version

3.23.81112

### 系统类型 / System type

Windows

### 系统版本 / System Version

22H2  22621.2134

**Comment by odomu** [comment]
那就重新下载安装

**Comment by cancundeyingzi** [comment]
重启即可
