### ISSUE TITLE
备份盘使用default_drive_id导致读取到资源盘的文件

### ISSUE THREAD

**Issue by cancundeyingzi** [odomu/aliyunpan#216]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [X] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

两个盘东西完全一样,但是实际上我备份盘几乎没东西
![image](https://github.com/odomu/aliyunpan/assets/73635883/86beb145-70be-4d95-a6bf-f75d271df5f8)
![image](https://github.com/odomu/aliyunpan/assets/73635883/451c85bf-0cb6-4e78-bb1c-a6c6e75080df)

### 复现步骤 / How to reproduce

/

### 软件版本 / App version

3.23.81112

### 系统类型 / System type

Windows

### 系统版本 / System Version

win11,22h2

**Comment by odomu** [comment]
![image](https://github.com/odomu/aliyunpan/assets/50035498/34f05a82-5d19-42b9-ba10-b82abb67fae1)
重置软件试试

**Comment by cancundeyingzi** [comment]
> 重置软件试试

已点击<删除全部数据(重置)>.重新登陆,依旧和原来一样         
![image](https://github.com/odomu/aliyunpan/assets/73635883/52e8be60-697b-422f-87bf-8e79dc6a5ae5)

**Comment by cancundeyingzi** [comment]
阅读了公告,请问备份盘用的是default_drive_id还是backup_drive_id?                  
![image](https://github.com/odomu/aliyunpan/assets/73635883/9e3d9757-e796-4f06-8e09-98c99e0450e1)

**Comment by odomu** [comment]
你去手机版登录一下就可以了

**Comment by cancundeyingzi** [comment]
> 你去手机版登录一下就可以了

手机版都用了好久了
![Screenshot_2023-08-12-18-32-22-042_com miui home](https://github.com/odomu/aliyunpan/assets/73635883/990bc1a9-b380-4884-815f-925c35cfbab8)

**Comment by odomu** [comment]
更新试试

**Comment by cancundeyingzi** [comment]
> 更新试试

.....还要更新什么...
![IMG_1756](https://github.com/odomu/aliyunpan/assets/73635883/dc5cb83f-35c0-4196-905a-0d72928cb6a4)

**Comment by cancundeyingzi** [comment]
493版本了也没用

**Comment by odomu** [comment]
> 493版本了也没用

我说的是更新这个软件

**Comment by cancundeyingzi** [comment]
已正常
