### ISSUE TITLE
下载包含文件数多的文件夹失败

### ISSUE THREAD

**Issue by timowei** [odomu/aliyunpan#22]
问题1：我试图用这个下载一个包含4.8万个文件、13000多个文件夹的文件夹，7个小时只断续下载了238M，而且中途经常出现状态显示为“解析中”但实际停止下载的情况。
原版V3在下载文件很多的文件夹情况下，也会出现卡顿，而且下载不完全。因此我此前一直用2.12.14版，不卡顿而且能把文件都下完。我看到介绍里测试下载4.4万个json文件也是用的V2版。

问题2：在设置→下载→新建下载任务时默认使用此路径、按照网盘完整路径保存，这两个选项取消选择的情况下，下载时不会跳出选择文件夹的窗口，无法下载（下图1，点那个开始下载没有任何反应），然后下方跳出提示图2：
图1：[https://s1.ax1x.com/2023/02/26/pppUnHJ.png](url)
图2：[https://s1.ax1x.com/2023/02/26/pppUKE9.png](url)

不知是否能解决这些问题呢？

**Comment by daniel-zou** [comment]
你为啥要下那么多？你内存够大吗？太多小文件，也会因为磁盘写性能受影响，程序挂起或暂停。个人作品，经不起这么折腾
