### ISSUE TITLE
无法下载，一直卡解析中

### ISSUE THREAD

**Issue by Bokey7** [odomu/aliyunpan#24]
软件：v3.10.24

于2023.2.25晚下载试用，可下载,
后于12点寝室断网期间，提前手段暂停，后电脑进入睡眠状态，并未关机
26日开机重新下载后，一直卡在解析中

**Comment by daniel-zou** [comment]
哪个平台？Windows？Linux？也可能是校园网问题。我这里文件多，或者大，有时也会出现一直解析问题，暂停后重新下载就好了。

**Comment by Bokey7** [comment]
> 

win10 22H2 我重启才行，尝试过暂停或者重启软件

**Comment by Bokey7** [comment]
> 哪个平台？Windows？Linux？也可能是校园网问题。我这里文件多，或者大，有时也会出现一直解析问题，暂停后重新下载就好了。

win10 22H2 我重启才行，尝试过暂停或者重启软件

**Comment by Bokey7** [comment]
> 哪个平台？Windows？Linux？也可能是校园网问题。我这里文件多，或者大，有时也会出现一直解析问题，暂停后重新下载就好了。

重启了系统
