### ISSUE TITLE
视频播放选项的建议

### ISSUE THREAD

**Issue by wqcblog** [odomu/aliyunpan#25]
由于播放软件不再内置
所以原有的MPV内置播放没有太大意义了
能否参照Alist启动播放的形式(给几个常用软件，用potplayer:// mpv://这些形式来启动
设置选项如下：(默认是自定义播放，和下载路径一样需要指定，如没有指定需提示)
自定义播放，网页播放，Potplayer播放，MPV播放。
仅是建议，供参考，谢谢

**Comment by 15109827573** [comment]
我直接把V2版本的MPV复制到制定目录，就可以在线播放了

**Comment by 15109827573** [comment]
您的来信我已收到
