### ISSUE TITLE
播放视频时，出现报错信息

### ISSUE THREAD

**Issue by devyujie** [odomu/aliyunpan#252]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [X] 最新版本是否存在此问题 / Latest app does not work
- [X] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

播放视频时报错，但是能正常播放

### 复现步骤 / How to reproduce

![image](https://github.com/odomu/aliyunpan/assets/48620527/21d273e6-0029-4327-bcbc-79c6f498ae35)

### 软件版本 / App version

3.24.1

### 系统类型 / System type

Windows

### 系统版本 / System Version

win10

**Comment by Theodore-98** [comment]
我也有同样的问题，刚才解决了
先设置另一个路径的播放器，我设置的是低版本的mpv，设置好以后随便找个文件播放，然后再找到最开始路径的mpv播放器就不会报错了

**Comment by odomu** [comment]
最新版本已修复
