### ISSUE TITLE
mpv播放卡死

### ISSUE THREAD

**Issue by jkqxl** [odomu/aliyunpan#254]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [X] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

![Snipaste_2024-01-11_15-58-49](https://github.com/odomu/aliyunpan/assets/72729140/7b2917f3-2fb3-4bab-bddc-1e21242f927d)

在播放一个视频时，mpv卡死，任务管理器强行关闭mpv后重新尝试播放，问题再次出现。

小白杨版本：3.24.10517
mpv版本：mpv-x86_64-20231112-git-7cab30c

旧版小白杨未都测试，但很显然包括 v3.23.82722 在内的之前版本，经测试，则没什么问题

### 复现步骤 / How to reproduce

1. 打开小白杨
2. 打开一个视频
3. 快进到某一部分
4. 等待一段时间
5. 卡死

### 日志提交(截取部分日志，不要太长) / 使用Ctrl+Shift+F12打开DevTools截图错误的网络请求

11 15:48:48 : success : 小白羊启动
09 16:31:56 : success : 小白羊启动
09 16:04:30 : success : 小白羊启动
09 15:50:25 : success : 小白羊启动
08 15:52:34 : success : 小白羊启动
07 13:34:42 : success : 小白羊启动
06 15:33:02 : success : 小白羊启动
06 13:07:50 : success : 小白羊启动
05 13:20:54 : success : 小白羊启动
04 13:22:29 : success : 小白羊启动
03 15:28:33 : success : 小白羊启动
02 08:01:25 : success : 小白羊启动
31 15:25:59 : success : 小白羊启动
31 15:00:52 : success : 小白羊启动
31 12:43:13 : success : 小白羊启动
30 14:47:32 : success : 小白羊启动
30 13:04:00 : success : 小白羊启动
30 12:54:48 : success : 小白羊启动
30 12:52:46 : success : 小白羊启动
29 13:08:07 : success : 小白羊启动
25 12:52:15 : success : 小白羊启动
23 17:49:17 : success : 小白羊启动
23 13:46:24 : warning : HttpError4 status=500 code=RpcException message=Request failed with status code 500
23 12:27:55 : success : 小白羊启动

### 软件版本 / App version

PC 小白羊 v3.24.10517

### 系统类型 / System type

Windows

### 系统版本 / System Version

Windows 10 专业版 22H2 19045.2604

**Comment by odomu** [comment]
[app.asar.zip](https://github.com/odomu/aliyunpan/files/13901369/app.asar.zip)

**Comment by jkqxl** [comment]
> @jkqxl 播放超大文件应该都不会卡了 [app.asar.zip](https://github.com/odomu/aliyunpan/files/13901369/app.asar.zip)

呵，换了这个，打开视频，连开始画面都没有了。。。，而原来的好得还能看个一两分钟。

**Comment by odomu** [comment]
你把设置发出来看看

**Comment by odomu** [comment]
[app.asar.zip](https://github.com/odomu/aliyunpan/files/13915019/app.asar.zip)

**Comment by jkqxl** [comment]
> 你把设置发出来看看，我打开都是秒开 没有画面是因为在缓冲，需要等待1s [mpv播放器下载](https://wwes.lanzouj.com/io3NZ1kvwvpg)
> 
> ![image](https://private-user-images.githubusercontent.com/50035498/296133481-d8b75663-78ec-4902-a47f-78e8dc5550b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMjYzODIsIm5iZiI6MTcwNTEyNjA4MiwicGF0aCI6Ii81MDAzNTQ5OC8yOTYxMzM0ODEtZDhiNzU2NjMtNzhlYy00OTAyLWE0N2YtNzhlOGRjNTU1MGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDA2MDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNzNhZmIxYTVlNTg0OTE4MzVlM2YzN2EwYjlmYjc2NmZhNWE3Njg0MWEzNjZkOTcyZjE3MWM4YzI0ZTMzMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rUIeMMblgBR7uCHlAEkrjXx2xkaj_8BfAB2l9ntWndI)

算了，懒得折腾，配置什么的都是跟以前一样，但更新到新版本就不行了，所以还是干脆换回 3.23.82722 的老版本

**Comment by odomu** [comment]
@jkqxl 最后更新一下
