### ISSUE TITLE
自定义播放软件播放视频出错

### ISSUE THREAD

**Issue by Pandaer13** [odomu/aliyunpan#257]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [X] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

自定义播放软件播放视频出错Cannot read properties of undefined (reading 'file_id') ，内置播放器不会
![PixPin_2024-01-13_14-02-07](https://github.com/odomu/aliyunpan/assets/25151055/54d7adca-e735-4e2f-899f-51bbb61a9cf7)

### 复现步骤 / How to reproduce

自定义播放软件，选择potplayer、mpv，然后播放任意视频都会出现

### 日志提交(截取部分日志，不要太长) / 使用Ctrl+Shift+F12打开DevTools截图错误的网络请求

``13 14:02:17 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'file_id') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'file_id')
    at Server.<anonymous> (file:///D:/alixby/resources/app.asar/dist/index.js:121:4208)
13 14:02:12 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'file_id') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'file_id')
    at Server.<anonymous> (file:///D:/alixby/resources/app.asar/dist/index.js:121:4208)
13 14:02:04 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'file_id') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'file_id')
    at Server.<anonymous> (file:///D:/alixby/resources/app.asar/dist/index.js:121:4208)
13 14:01:57 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'file_id') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'file_id')
    at Server.<anonymous> (file:///D:/alixby/resources/app.asar/dist/index.js:121:4208)
13 14:01:50 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'file_id') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'file_id')
    at Server.<anonymous> (file:///D:/alixby/resources/app.asar/dist/index.js:121:4208)
13 14:01:44 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'file_id') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'file_id')
    at Server.<anonymous> (file:///D:/alixby/resources/app.asar/dist/index.js:121:4208)
13 14:01:20 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'file_id') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'file_id')
    at Server.<anonymous> (file:///D:/alixby/resources/app.asar/dist/index.js:121:4208)
13 14:00:03 : danger : unhandledrejection 
//== Error ==//
 Cannot read properties of undefined (reading 'file_id') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading 'file_id')
    at Server.<anonymous> (file:///D:/alixby/resources/app.asar/dist/index.js:121:4208)
13 13:58:14 : success : 小白羊启动
``

### 软件版本 / App version

3.24.11310

### 系统类型 / System type

Windows

**Comment by odomu** [comment]
[Uploading app.asar.zip…]()

**Comment by odomu** [comment]
[app.asar.zip](https://github.com/odomu/aliyunpan/files/13927217/app.asar.zip)

**Comment by Pandaer13** [comment]
> [app.asar.zip](https://github.com/odomu/aliyunpan/files/13927217/app.asar.zip)

OK了大佬
