### ISSUE TITLE
和Motrix似乎有冲突

### ISSUE THREAD

**Issue by KangMz** [odomu/aliyunpan#26]
如果运行了 Motrix 再运行此项目。会提示aria2本地连接已断开，并且会导致原本浏览器调用motrix下载时会提示 认证失败。
关闭此项目后 Motrix可以正常使用，或关闭Motrix再启动此项目，也不会出现 aria2本地连接已断开提示

**Comment by NJYZ-96** [comment]
同样，
![截图_20230311152304](https://user-images.githubusercontent.com/125748593/224471136-9325b32a-494b-4200-bb21-2384a1d857ea.png)
