### ISSUE TITLE
热更新后再次打开软件出现报错信息

### ISSUE THREAD

**Issue by devyujie** [odomu/aliyunpan#261]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [X] 最新版本是否存在此问题 / Latest app does not work
- [X] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

![image](https://github.com/odomu/aliyunpan/assets/48620527/e631aaaf-b7d4-4a40-84f9-311b7ae57346)

### 复现步骤 / How to reproduce

热更新后再次打开软件出现报错信息

### 软件版本 / App version

11622

### 系统类型 / System type

Windows

### 系统版本 / System Version

win10

**Comment by RinSky123** [comment]
这个正常啊，退出再打开一次就好了
