### ISSUE TITLE
无法进入文件夹

### ISSUE THREAD

**Issue by tsunamilx** [odomu/aliyunpan#275]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [X] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

无法进入文件夹，点击或者双击文件夹都只是原地刷新

### 复现步骤 / How to reproduce

![PixPin_2024-01-31_12-14-34](https://github.com/odomu/aliyunpan/assets/6290337/4fc4195b-b9a9-4a0e-9b2c-c1d3a04cf4dc)

### 软件版本 / App version

3.24.12922

### 系统类型 / System type

Windows

**Comment by gdgdstudy95** [comment]
遇到相同问题了

**Comment by odomu** [comment]
https://github.com/odomu/aliyunpan/issues/276

**Comment by hecarli555** [comment]
一样的问题。。。。

**Comment by null119** [comment]
问题一样，补充网络请示错误日志
## 日志提交
01 09:22:39 : warning : HttpError4 status=400 code=BadRequest message=Request failed with status code 400
01 09:22:39 : warning : HttpError4 status=400 code=BadRequest message=Request failed with status code 400
01 09:22:38 : warning : HttpError4 status=400 code=BadRequest message=Request failed with status code 400
01 09:22:38 : warning : HttpError4 status=400 code=BadRequest message=Request failed with status code 400
01 09:22:37 : warning : HttpError4 status=400 code=BadRequest message=Request failed with status code 400
01 09:22:37 : warning : HttpError4 status=400 code=BadRequest message=Request failed with status code 400
## DevTools截图
![image](https://github.com/odomu/aliyunpan/assets/42354276/741e5c2b-edb9-4ae4-aba8-695d58593a5b)

**Comment by Hiraly-wang** [comment]
遇到相同的问题

**Comment by tsunamilx** [comment]
用了TG频道里的包（app.asar），覆盖 app.asar 到 安装目录/resources 下的同名文件，问题解决了
