### ISSUE TITLE
无法改变窗口大小

### ISSUE THREAD

**Issue by devyujie** [odomu/aliyunpan#285]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [X] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

窗口无法改变大小

### 复现步骤 / How to reproduce

窗口无法改变大小

### 软件版本 / App version

3.24.30100

### 系统类型 / System type

Windows

### 系统版本 / System Version

win10

**Comment by cyao2q** [comment]
我测试了下 不是无法更改大小 而是 最小值 掉大了 低分辨率屏幕就表现为 无法调整大小了

**Comment by odomu** [comment]
因为窗口小了按钮显示不全
