### ISSUE TITLE
最新版使用外部MPV播放视频后，播放几分钟后会卡死。外部调用PotPlayer播放视频无法播放

### ISSUE THREAD

**Issue by pengpai0124** [odomu/aliyunpan#292]
### 确认问题 / Assignments

- [X] 不存在相似或相关的issue（**搜索以前issue**） / No similar or related issues
- [X] 不存在相似或相关的**Wiki**问题说明 / No similar or related wiki
- [x] 最新版本是否存在此问题 / Latest app does not work
- [ ] 旧版本是否存在此问题 / Oldest app does not work

### 问题描述 / Describe Bugs

最新版使用外部MPV lazy播放视频后，可以正常启动播放，但播放几分钟后会卡死。尝试了mpv -lazy、mpv-ousc等都是这样。外部调用PotPlayer播放视频无法播放

### 复现步骤 / How to reproduce

直接使用外部MPV lazy播放视频即可复现，可以正常启动播放，但播放几分钟后会卡死。，尝试了mpv -lazy、mpv-ousc等都会卡死。

### 日志提交(截取部分日志，不要太长) / 使用Ctrl+Shift+F12打开DevTools截图错误的网络请求

<img width="559" alt="屏幕截图 2024-03-16 091556" src="https://github.com/odomu/aliyunpan/assets/5155434/61fbeb5d-4703-4b0b-82b1-ea94fbccf729">
<img width="596" alt="屏幕截图 2024-03-16 092002" src="https://github.com/odomu/aliyunpan/assets/5155434/06d7b788-86f2-48e0-b6a7-892317df2e81">

### 软件版本 / App version

3.24.31522

### 系统类型 / System type

Windows

### 系统版本 / System Version

Windows 11 专业版

**Comment by odomu** [comment]
网络错误，重新登陆账号
