### ISSUE TITLE
项目重要说明

### ISSUE THREAD

**Issue by odomu** [odomu/aliyunpan#299]
### 项目说明
 - 因为当前项目更新后立马会被魔改【本来也不想管，但是现在已经触及底线】，以后可能停止更新，
 - 强烈抵制魔改强制收费的行为，不要白嫖我的劳动力，开源不等于自由软件😦😦😦😦😦😦😦😦😦
 - 所有提交记录都可以查到。**因为该软件并没有什么人用 ，可能都不会看到这些话，我只能说且行且珍惜**。

### 项目历史
![image](https://github.com/odomu/aliyunpan/assets/50035498/738c7acb-0cd0-4026-b8bb-b17c9faed353)

https://github.com/gaozhangmin/aliyunpan

**Comment by aunsen** [comment]
这个才是正牌血统？

**Comment by ihehui** [comment]
好像去年gaozhangmin就已经在用你的代码了，不过只提过一次，也就是那时开始搞收费的。建议UP主把上面的内容放到主页上去，让大家了解真相

**Comment by gaozhangmin** [comment]
我确实把一部分功能 弄过来了。这个我承认。我觉得我们半斤八两吧， 当初你也抄袭了很多我的。

**Comment by gaozhangmin** [comment]
新版本  我已经把你的功能都下掉了，全部都是我自己的版本了。

**Comment by odomu** [comment]
@gaozhangmin 功能可以相似，但是直接复制代码并且不声明就有问题了

**Comment by gaozhangmin** [comment]
> @gaozhangmin 功能可以相似，但是直接复制代码并且不声明就有问题了

新版本 我会去掉你的功能。等这几天我发布

**Comment by odomu** [comment]
希望以后尊重开源精神

**Comment by gaozhangmin** [comment]
@odomu  3.13.2 已经去掉所有你的代码。

**Comment by jiaoting** [comment]
感觉还是odomu的版本用起来UI美观，功能全面而且简洁，gaozhangming的功能看起来应该是准备走vip收费路线了，我倒是一般用不到那些功能

**Comment by AnnieSmile** [comment]
> 感觉还是odomu的版本用起来UI美观，功能全面而且简洁，gaozhangming的功能看起来应该是准备走vip收费路线了，我倒是一般用不到那些功能

gaozhangming确实走收费路线了

**Comment by wangkun19930608** [comment]
赞一个！

**Comment by HumanMus1c** [comment]
感谢大佬的付出！
