### ISSUE TITLE
能不能导出token？

### ISSUE THREAD

**Issue by haig233** [odomu/aliyunpan#31]
能不能导出token？我有个账号，接码登录的，手机上也没有了，那个号码也没办法再接码了，能不能直接导出token？或者cookie

**Comment by lrs95** [comment]
这里可以很方便的获取token：https://alist.nn.ci/zh/guide/drivers/aliyundrive.html

**Comment by haig233** [comment]
> 这里可以很方便的获取token：https://alist.nn.ci/zh/guide/drivers/aliyundrive.html

我不是获取不到token，我是有个号，可以说是死号，登录了小白羊的，没办法导出已经在小白羊登录的这个token，因为我那个号已经登不回去了，所以我唯一的办法就是只能看下作者能不能做个导出小白羊token的功能
