### ISSUE TITLE
Mac arm64版本登陆后一直报错

### ISSUE THREAD

**Issue by Bssn520** [odomu/aliyunpan#35]
如图所示：
<img width="505" alt="image" src="https://user-images.githubusercontent.com/96654048/221479282-230686ab-a556-4bbc-bf72-d31ee7bc2f93.png">
请问是bug还是我哪里设置的不对？
求指教！

**Comment by Bssn520** [comment]
> 能不能分享下Mac版的包

https://github.com/odomu/aliyunpan/issues/2#issuecomment-1445264962

**Comment by lrs95** [comment]
> 如图所示： <img alt="image" width="505" src="https://user-images.githubusercontent.com/96654048/221479282-230686ab-a556-4bbc-bf72-d31ee7bc2f93.png"> 请问是bug还是我哪里设置的不对？ 求指教！

我去看了下好像说是bug，给的解决方法是可以启动任何一个aria2 在小白羊里填写端口号等配置 切换即可 或者 有相关经验或基础，可以另外建一个 Aria2 下载服务
【Mac下如何安装使用Aria2（免HomeBrew）：https://zhuanlan.zhihu.com/p/561726501】。
具体怎么操作我就不清楚了，我主要用windows。

**Comment by Bssn520** [comment]
> > 如图所示： <img alt="image" width="505" src="https://user-images.githubusercontent.com/96654048/221479282-230686ab-a556-4bbc-bf72-d31ee7bc2f93.png"> 请问是bug还是我哪里设置的不对？ 求指教！
> 
> 我去看了下好像说是内置的aria2的bug，给的解决方法是可以启动任何一个aria2 在小白羊里填写端口号等配置 切换即可 或者 有相关经验或基础，可以另外建一个 Aria2 下载服务 【 [Mac下如何安装使用Aria2（免HomeBrew）](https://zhuanlan.zhihu.com/p/561726501)】 具体怎么操作我就不清楚了，我主要用windows。

好的，感谢🙏！
等啥时候alist不能挂载阿里云盘分享之后再用，感觉没有alist方便。

**Comment by missuo** [comment]
已经修复 https://github.com/missuo/AliyunPanMac/releases

**Comment by Bssn520** [comment]
> 已经修复 https://github.com/missuo/AliyunPanMac/releases

仍然报错：
<img width="623" alt="image" src="https://user-images.githubusercontent.com/96654048/224549204-771bbf5a-6834-401f-b4c6-3df6f0bda827.png">

版本：
<img width="309" alt="image" src="https://user-images.githubusercontent.com/96654048/224549192-9af3d287-8a81-468a-9fbe-a3035ffe1eb4.png">

**Comment by Bssn520** [comment]
> > 已经修复 https://github.com/missuo/AliyunPanMac/releases
> 
> 仍然报错： <img alt="image" width="623" src="https://user-images.githubusercontent.com/96654048/224549204-771bbf5a-6834-401f-b4c6-3df6f0bda827.png">
> 
> 版本： <img alt="image" width="309" src="https://user-images.githubusercontent.com/96654048/224549192-9af3d287-8a81-468a-9fbe-a3035ffe1eb4.png">

macos arm64版本.

**Comment by missuo** [comment]
我也是ARM64，让别的朋友也测试过了，请问你是什么系统版本？我排查一下问题。

**Comment by Bssn520** [comment]
> 我也是ARM64，让别的朋友也测试过了，请问你是什么系统版本？我排查一下问题。

系统：ventura 13.2
感谢！

**Comment by missuo** [comment]
@Bssn520 我找到的问题是内置aria2的Path不对。但是已经修复过了，奇怪的是到目前为止除了你之外，有另外一位网友反馈也有问题。如果你会Build，你可以尝试一下Git Clone一下我的代码，重新Build测试一下。

**Comment by Bssn520** [comment]
抱歉啊，没有搞过开发，不太懂。 @missuo

**Comment by jzhw** [comment]
> @Bssn520 我找到的问题是内置aria2的Path不对。但是已经修复过了，奇怪的是到目前为止除了你之外，有另外一位网友反馈也有问题。如果你会Build，你可以尝试一下Git Clone一下我的代码，重新Build测试一下。

m1 mpb 同样报错
ventura 13.2.1

**Comment by Bssn520** [comment]
> > @Bssn520 我找到的问题是内置aria2的Path不对。但是已经修复过了，奇怪的是到目前为止除了你之外，有另外一位网友反馈也有问题。如果你会Build，你可以尝试一下Git Clone一下我的代码，重新Build测试一下。
> 
> m1 mpb 同样报错 ventura 13.2.1

我安装aria2之后就可以正常使用了：
```brew install aria2```
