### ISSUE TITLE
怎么安装包不见了?

### ISSUE THREAD

**Issue by onvz** [odomu/aliyunpan#43]
在哪里可以下载安装包?

**Comment by lvxing8686** [comment]
> 

好像是，悲催，我2个号。

**Comment by Sunovn** [comment]
一直不知道怎么下载，谁教一下

**Comment by onvz** [comment]
> 一直不知道怎么下载，谁教一下

之前在这个地址里是有的,
[https://github.com/odomu/aliyunpan/releases](url)
现在没有了,

是要自己编译吗?? 求教程

**Comment by zlbwswws95** [comment]
https://github.com/odomu/aliyunpan/actions
在这里下载安装包

**Comment by Sunovn** [comment]
> https://github.com/odomu/aliyunpan/actions 在这里下载安装包

我知道，然后呢

**Comment by onvz** [comment]
> https://github.com/odomu/aliyunpan/actions 在这里下载安装包

感谢,下载到了,,不过很奇怪,用内置的网页播放器速度可以播放的很流畅,但是用本地的mpv,就会很差,只有几百k,是内置的播放器有黑科技吗??

下载速度依然和之前的一样只有几百K,

**Comment by Sunovn** [comment]
> > > https://github.com/odomu/aliyunpan/actions 在这里下载安装包
> 
> > 
> 
> > 我知道，然后呢
> 
> 
> 
> 在网页的最下面

是fixbuild下面的Artifacts？我之前点了很多次但是并没有下载

**Comment by 285516316** [comment]
> > > > https://github.com/odomu/aliyunpan/actions 在这里下载安装包
> > 
> > 
> > > 
> > 
> > 
> > > 我知道，然后呢
> > 
> > 
> > 在网页的最下面
> 
> 是fixbuild下面的Artifacts？我之前点了很多次但是并没有下载

点那个build记录 （最近一次是 https://github.com/odomu/aliyunpan/actions/runs/4455171022 ），进去后在网页的最下面

**Comment by onvz** [comment]
> > 点那个build记录 （最近一次是 https://github.com/odomu/aliyunpan/actions/runs/4455171022 ），进去后在网页的最下面
> 
> 那不就是Artifacts了？

点进去在最下面,有3个版本的可以下载,,不过,在线观看和下载还是很慢

**Comment by weakestan** [comment]
这个版本发布当天还是很好用，第二天好像就限速了。所以在线没法看了。
