### ISSUE TITLE
在线点播与下载速度极慢

### ISSUE THREAD

**Issue by zksd2022** [odomu/aliyunpan#45]
在线播放速度只有不到200k  下载600K   都是超会账号  换蜗牛云盘下载都是20m
问题出在哪里？

**Comment by snow212-cn** [comment]
问题出在作者 什么都不解决

**Comment by yaozijin** [comment]
> 在线播放速度只有不到200k 下载600K 都是超会账号 换蜗牛云盘下载都是20m 问题出在哪里？

6

**Comment by shemengjia** [comment]
我也是，下载速度几百KB
