### ISSUE TITLE
反复弹出：Aria2本地连接已断开

### ISSUE THREAD

**Issue by liuyun198833** [odomu/aliyunpan#54]

**Comment by maomaochong199** [comment]
https://github.com/gaozhangmin/aliyunpan/issues/5#issuecomment-1510358153

现在还有一个bug就是路径不能含空格和中文名，过几天上面项目可能会发布修复方法

**Comment by whkrain** [comment]
一直提示声称链接失效，无法下载

**Comment by odomu** [comment]
下载最新版本试试

**Comment by liuyun198833** [comment]
@odomu  谢谢大佬，更新版中Aria2这个问题已经解决了。但点击启用OpenApi按钮不正常，没法开启，一直是灰显。

**Comment by odomu** [comment]
@liuyun198833
![image](https://user-images.githubusercontent.com/50035498/235084650-86c26e91-4427-45c3-8b0e-649f031cb487.png)

**Comment by rosspsp** [comment]
大神，windows，action中下载的最新的，无法开启OpenApi，点击按钮还是灰色，并提示refresh_token不能为空，已经删除全部数据（重置），还是不行
![image](https://user-images.githubusercontent.com/73610222/235087466-b67f1f0b-0680-4144-9e7f-f721d6436aa4.png)

**Comment by liuyun198833** [comment]
@odomu 大佬，openApi设置应该跟账号对应，现在设置一个账号后所有账号都是同一个token,一样只有一个账号是使用正常的。所以有个小建议，不知道大佬能否采纳。

**Comment by odomu** [comment]
@liuyun198833 这下应该都可以了

**Comment by rosspsp** [comment]
@odomu 大神测试了一下，open-api可以进行设置了。能不能提一个小bug？就是，mac端不能正常调用mpv播放器，播放视频时，无论选择"本地mpv播放器"还是“手动自定义”，mpv闪一下就消失了。。。
<img width="634" alt="image" src="https://user-images.githubusercontent.com/73610222/235115499-59c58669-7a95-4e64-b4f9-f706f2350310.png">

**Comment by rosspsp** [comment]
@odomu 大神，最新编译的open-api多账户版本，无法获取access_token
<img width="632" alt="image" src="https://user-images.githubusercontent.com/73610222/235119863-e21e5095-80cf-4812-9428-e38116eed67e.png">

**Comment by odomu** [comment]
@rosspsp AccessToken下载时自动获取

**Comment by rosspsp** [comment]
@odomu 我估计是我refresh token，刷新多了，“自动刷新AccessToken后请勿删除，防止多次请求Outh令牌链接“
”

**Comment by rosspsp** [comment]
@odomu 我又测试了一下，是因为如果直接用网页播放器，则access_token刷新不出来，如果调用第三方播放器，如iina，access_token才可以刷新出来。。。然后，网页播放器也可以正常播放了。。。。

**Comment by rosspsp** [comment]
@odomu 大神，能否修复一下mac下的mpv播放器调用问题？感谢！！！感谢！！！！！

**Comment by liuyun198833** [comment]
@odomu 大佬，完美解决。另关于文件去重功能有个小建议，开个新issue，看大家的需要，大佬酌情修改

**Comment by odomu** [comment]
@rosspsp 没有Mac设备无法修复，请自行查找原因🦊
