### ISSUE TITLE
请教，怎么申请OpenApi账号

### ISSUE THREAD

**Issue by hangxj** [odomu/aliyunpan#57]
请教，怎么申请OpenApi账号

**Comment by odomu** [comment]
https://survey.alibaba.com/apps/zhiliao/I9Dd1Nl89

**Comment by blibilijojo** [comment]
> https://survey.alibaba.com/apps/zhiliao/I9Dd1Nl89

咋弄Oauth令牌链接，另外两个都行了

**Comment by hangxj** [comment]
> https://survey.alibaba.com/apps/zhiliao/I9Dd1Nl89

谢谢
