### ISSUE TITLE
会有一定概率调用potplayer出现一直加载不播放的情况。

### ISSUE THREAD

**Issue by lrs95** [odomu/aliyunpan#6]
有时候设置里切换成内置mpv播放一下再切回pot就好了，很奇怪。

**Comment by thouser8** [comment]
我的是内置mpv和调用potplayer都没反应。。

**Comment by xingsuxingchen** [comment]
调用potplayer时每次播放都需要加载好久，播放过程还有卡顿现象

**Comment by thouser8** [comment]
> 调用potplayer时每次播放都需要加载好久，播放过程还有卡顿现象

已找到解决方法，在高级选项中选择删除全部数据（重置），然后自动重启再重新登录账号即可。

**Comment by xingsuxingchen** [comment]
> > 调用potplayer时每次播放都需要加载好久，播放过程还有卡顿现象
> 
> 已找到解决方法，在高级选项中选择删除全部数据（重置），然后自动重启再重新登录账号即可。

还是那种效果，中间卡顿似乎更严重啦！哈哈哈~~~

**Comment by xingsuxingchen** [comment]
作者liupan的小白羊版本至今都未更新，以前用他的感觉顺畅些
