### ISSUE TITLE
修复任务栏图标问题（描述无力，看图片吧）

### ISSUE THREAD

**Issue by blibilijojo** [odomu/aliyunpan#61]
![image](https://user-images.githubusercontent.com/102420734/235298527-6d5fcd7d-ef7c-493b-b541-86ccef1c7f6a.png)
就是这个问题

**Comment by blibilijojo** [comment]
软件运行之后不会覆盖任务栏订上的

**Comment by maomaochong199** [comment]
我win7确实有这个问题，你是win7吗

**Comment by blibilijojo** [comment]
> 我win7确实有这个问题，你是win7吗，win7订上的图标是v2版的信息

看我的任务栏样式就能看出来了，win7
