### ISSUE TITLE
根目录的折叠

### ISSUE THREAD

**Issue by wqiucheng** [odomu/aliyunpan#62]
作者，你好，左侧边栏根目录可以添加折叠按钮吗？目前文件夹有，但是根目录没有。另外目前登录必须还要扫码用老api，这是因为新api不能用部分功能吗？

**Comment by blibilijojo** [comment]
> 作者，你好，左侧边栏根目录可以添加折叠按钮吗？目前文件夹有，但是根目录没有。另外目前登录必须还要扫码用老api，这是因为新api不能用部分功能吗？

是的，新api功能少，但是不限速，所以要想达到以前小白羊的效果，一般都需要用两个api
