### ISSUE TITLE
这是什么情况？

### ISSUE THREAD

**Issue by xy0124** [odomu/aliyunpan#65]
![image](https://user-images.githubusercontent.com/99000021/235393076-ad753f5e-e5ac-4948-b0f2-e9e159104f87.png)

**Comment by killdayu** [comment]
我的Mac m1也是

**Comment by justice6688** [comment]
记得把本地缓存给清理一下就正常使用了

**Comment by Cyiming** [comment]
> 记得把本地缓存给清理一下就正常使用了

是缓存路径中的 清理缓存么 还是不行

https://github.com/odomu/aliyunpan/issues/65#issuecomment-1529809847

**Comment by Andyqi0076** [comment]
安装文件不要在有空格的文件夹内，另外好像其他软件占用了aria2端口也会这样

**Comment by justice6688** [comment]
https://github.com/odomu/aliyunpan/issues/65#issuecomment-1531497995
还有就是下载的时候报错，显示已出错：aria2cDNS解析失败，之前还好好的

**Comment by SurpassHR** [comment]
你这是路径中含有空格了
