### ISSUE TITLE
一直在加载用户信息

### ISSUE THREAD

**Issue by ublock-ghost** [odomu/aliyunpan#7]
![image](https://user-images.githubusercontent.com/89686335/221241698-c196ecb2-0432-4402-ae46-1bcf3ad093c1.png)

**Comment by lrs95** [comment]
清楚全部数据

**Comment by lrs95** [comment]
![image](https://user-images.githubusercontent.com/24587454/221306802-8d28fed5-0511-49fe-8508-8bbe4621a0a1.png)

**Comment by ublock-ghost** [comment]
> 清楚全部数据

感谢老哥，可以了
