### ISSUE TITLE
建议RefreshToken的获取改为软件内部获取

### ISSUE THREAD

**Issue by blibilijojo** [odomu/aliyunpan#74]
既然AList网页中支持扫码获取和登录获取，为啥不能直接像小白羊登录账号一样内置到软件内部呢
![image](https://user-images.githubusercontent.com/102420734/235931540-b613cd57-5bdd-47e3-b6e0-57fa3cf97859.png)
可以修改为登录账号后再出现一次登录获取RefreshToken，或者像现在一样在设置中也可以单独登录获取RefreshToken
ps：主要是有的人连这个都不会就离谱

**Comment by rosspsp** [comment]
我猜作者没有这样设置的原因有两点：
1.获取access_token的方法不止这一种（通过alist），留“Oauth令牌链接”，是让软件更加自由，可以用其它获取token的方式（如clouddrive2）。
2.毕竟这是阿里给人家alist开发者进行调用的，直接内置在软件内，不合适吧。。。

**Comment by blibilijojo** [comment]
> 我猜作者没有这样设置的原因有两点： 1.获取access_token的方法不止这一种（通过alist），留“Oauth令牌链接”，是让软件更加自由，可以用其它获取token的方式（如clouddrive2）。 2.毕竟这是阿里给人家alist开发者进行调用的，直接内置在软件内，不合适吧。。。

啊.......不清楚
