### ISSUE TITLE
请问为什么要切换成openapi接口了

### ISSUE THREAD

**Issue by maomaochong199** [odomu/aliyunpan#80]
因为老的接口会关闭么，有什么优缺点，这不会增加很多工作量么

**Comment by blibilijojo** [comment]
> 因为老的接口会关闭么，有什么优缺点，这不会增加很多工作量么

额，老接口会限速啊.......没看到第一条“添加OpenApi支持，兼容旧版Api，加速视频播放和下载”吗........
