### ISSUE TITLE
修复一下转存的一些问题

### ISSUE THREAD

**Issue by blibilijojo** [odomu/aliyunpan#83]
![image](https://user-images.githubusercontent.com/102420734/236664951-648117be-4c16-4c7f-8d5f-150d8531a8e3.png)
如果我这样直接按路径导入的话他会给我吧前面几个没用的大文件夹路径也套上来，我希望只转存我选择的那一个文件夹

**Comment by Andyqi0076** [comment]
并不会的，我一直这样导入，只勾选自己需要的就行
