### ISSUE TITLE
最新版小白羊在线播放视频功能失效

### ISSUE THREAD

**Issue by thouser8** [odomu/aliyunpan#98]
如图所示，无论播放原始视频还是转码，以及无论选择什么播放器都会报错。
![image](https://github.com/odomu/aliyunpan/assets/83090571/b60a1a26-1869-4a03-ac14-f5b5bdfb4801)

**Comment by odomu** [comment]
这个可能是违规视频，无法在线播放

**Comment by thouser8** [comment]
> 这个可能是违规视频，无法在线播放

但是换用其他第三方云盘（如蜗牛云盘）是能够正常播放的，官方客户端也没问题

**Comment by odomu** [comment]
那我晚上看看

**Comment by thouser8** [comment]
好的已经修复了，感谢作者
