### ISSUE TITLE
视频播放问题

### ISSUE THREAD

**Issue by JessBobby** [odomu/aliyunpan#99]
调用外部播放器（potplayer 64位版220420(1.7.21632)）播放时需要完全缓冲视频后才能观看。
未使用内置的播放器，暂不清楚是否也有此问题
笔记本电脑：win10 家庭版21H2 19044.1889
云盘版本：3.10.28 ，上一版本未出现此问题。
删除缓存，数据库，重置后均无法解决。

**Comment by odomu** [comment]
@JessBobby 更新试试

**Comment by JessBobby** [comment]
> @JessBobby 更新试试

谢谢！更新后成功解决该问题。
